---
- hosts: droplets
  tasks:
    - name: "Install forever (to run Node.js app)."
      npm: name=forever global=yes state=latest

    - name: create M3
      file: path=/M3 state=directory

    - name: unzip and copy to destination
      unarchive: src='App.zip' dest='/M3/' copy='yes'

    - name: npm install
      npm: path=/M3/App

    - name: "Start example Node.js app."
      command: forever start /M3/App/app.js
