---
- hosts: droplets
  tasks:

    - name: create M3
      file: path=/M3 state=directory

    - name: Copying redis info file
      copy: src='App/redis_server.json' dest='/'

    - name: Copying redisAlert.js info file
      copy: src='redisAlert.js' dest='/'

    - name: Copying redisAlert.js package.json
      copy: src='package.json' dest='/'

    - name: npm install
      npm: path=/

    - name: unzip App and copy to destination
      unarchive: src='App.zip' dest='/M3/' copy='yes'

    - name: npm install
      npm: path=/M3/App

    - name: "Start Node.js app."
      command: forever start /M3/App/app.js
