---
- hosts: droplets
  tasks:

    - name: create M3
      file: path=/M3 state=directory

    - name: create Monitoring
      file: path=/Monitoring state=directory

    - name: unzip App and copy to destination
      unarchive: src='App.zip' dest='/M3/' copy='yes'

    - name: npm install
      npm: path=/M3/App

    - name: "Start example Node.js app."
      command: forever start /M3/App/app.js
