---
- hosts: droplets
  tasks:
    - name: Installing nodeJs
      apt: pkg=nodejs state=installed update_cache=true

    - name: Installing npm
      apt: pkg=npm state=installed update_cache=true

    - name: Installing unzip
      apt: pkg=unzip state=installed update_cache=true

    - name: Linking nodejs to run as "node"
      command: ln -s /usr/bin/nodejs /usr/bin/node

